### ISSUE TITLE
Clean Install Walkthrough Flow

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence-vscode#116]
## Steps To Reproduce

Clean install of VSCode and Evidence Extension.

You need to [fully remove VSCode files](https://stackoverflow.com/questions/42603103/how-to-completely-uninstall-vs-code-on-mac) from your system first

> Just downloaded VSCode Insiders (which is their prerelease) and installed the VSCode Extension
> 
> I suspect this replicates a “Clean install” of the Evidence extension.
> 
> It boots the walkthrough after installing.
> 
> This is now kind of broken, as it prompts you to start Evidence without having a project open.

### Environment

- VSCode Extension version (Check in VSCode Marketplace): 
- Node version (`node -v`):
- npm version (`npm -v`):
- Database:

## Expected Behavior

Have the “start Evidence” command check whether it is in an evidence project, and if not, then it runs the “create new evidence project” command

## Actual Behaviour

Boots walkthrough: start Evidence button does not work as not inside an Evidence project
![insiders-install](https://github.com/evidence-dev/evidence-vscode/assets/58074498/019bacad-cd31-422f-9d7a-463e4c182ab8)

**Comment by hughess** [comment]
Added a PR for one option (#117) - show a Create Project button only when an Evidence project is not detected
