### ISSUE TITLE
Rev 1 feedback 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence-vscode#24]
Really cool overall, I could see myself using it for sure. 

### Nits and bugs 

- Start server -- I see a blank simple browser while the project boots, but it never seems to clear for me. I have to hit reload to get it up. 
- Start server, and the preview command do the same thing. I think for clarity we should only offer one command. My preference would be "start dev server". If there's a convention for "preview" that's ok too, but just one. Change should also be reflected in the tooltip for the button in the status bar.  
- I think commands which kill the dev server (stop server, update, install etc.) should shut the simple browser preview window. Today it stays visible, but the app is in a broken state when the dev server is shut down, and it won't respond to updates in markdown. 
- After initializing from the template, or re-opening vscode, I don't see the start dev server shortcut in the status bar until I have actually opened a .md file. I think the command should be visible in the status bar at all times when you are in a workspace which contains an Evidence project. 

### Gifs 

![CleanShot 2023-05-29 at 21 06 13](https://github.com/evidence-dev/evidence-vscode/assets/6857673/360cb96e-c301-407f-8bf8-2face2585d26)
![CleanShot 2023-05-29 at 19 13 59@2x](https://github.com/evidence-dev/evidence-vscode/assets/6857673/a2b00488-6ac4-40c5-b388-ed7e4a0ab539)

**Comment by RandomFractals** [comment]
> * I think commands which kill the dev server (stop server, update, install etc.) should shut the simple browser preview window. Today it stays visible, but the app is in a broken state when the dev server is shut down, and it won't respond to updates in markdown.

I researched this yesterday and shared preliminary info in the private vscode dev slack channel. Since you have decided not to make that channel that contains all my daily notes and updates public, here is the update on this:

>looking the built-in simple browser implementation I don't see a quick and easy way for us to open it on the side, or change that webview title and icon. So, if we want to see more stylized Evidence built-in browser and have more open/close/reload page options, we'd need to invest time into implementing our own. ... https://github.com/microsoft/vscode/blob/main/extensions/simple-browser/src/extension.ts

**Comment by RandomFractals** [comment]
Closing this initial ext. review ticket as all the listed issues above have been addressed, or pulled into new feature/enhancement tickets.
