### ISSUE TITLE
Organizing around the project rather than the markdown file 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence-vscode#25]
I might have the wrong mental model about vs code extensions, but after playing with this, I wonder if this might be a reasonable way forward on a couple items. 

I think we should have the extension detect whether or not there is an Evidence project in the current VS code workspace, and use that information to determine which status bar items, or command palette items are available. 

If it's possible to use that same approach to decide how to treat .md files, I also think that would be a sensible way to go. 

### Detecting an Evidence project 
- For the foreseeable future, any package.json which includes an "@evidence-dev/evidence" dependency could be safely assumed to be in the root of an evidence project  
- Monorepos 
- Users co-locate their evidence projects in monorepos. It won't be safe to assume that the above package.json will be in the root of workspace. 
- If we find the project root in another directory, all of the status bar / command palette commands should be run with their working directory set to the root of the evidence project, whether it's the root of the workspace or not. 

### Treatment of status bar items / commands 
When an evidence project is detected in the workspace, we should offer all of the commands and status bar items, regardless of what files are open in vscode. 

Eventually we might have some commands which are file specific, but right now all of them are project-level. 

### Treatment of markdown files 

It seems like we're facing some weird trade-offs to have the extension whether or not we can safely override the built in markdown features

The options so far are: 
- Create a new file extension, e.g .emd 
- Add some flags to frontmatter 
- Write some sort of detection logic to parse markdown and judge 
- ? 

If it's possible to use logic beyond just the file extension to determine how to treat the file, I think we could use the above approach to make a simpler judgements about how to treat the .md files that the extension encounters: 

1. All .md files inside project-root/pages can safely be treated as evidence markdown 
2. All .md files outside of project-root/pages should be treated as regular markdown 

For example, the [readme.md](http://readme.md/) in the root of an evidence project should not be treated like evidence markdown.

**Comment by RandomFractals** [comment]
Most of the listed loose ends in this ticket were already resolved. See other referenced tickets.

The rest will be handled in #64 and other markdown related tickets.
