### ISSUE TITLE
Update command installs @ latest

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence-vscode#26]
Just want to leave this as a flag for us in the future, no action required. 

This is totally fine for now, but eventually it seems like we should be respecting whatever version semver users have in their project (e.g. they are only accepting minor bumps).

**Comment by RandomFractals** [comment]
Closing this as it's not an actionable or workable ticket.

Please reopen when you decide what you'd like to change for the "latest" packages update.
