### ISSUE TITLE
Align status bar tooltip to command palette name 

### ISSUE THREAD

**Issue by mcrascal** [evidence-dev/evidence-vscode#32]
Fine tuning -- not for current release 

Command palette: "Start server" 
Status bar tooltip: "Start dev server" 

Command palette: "Stop server" 
Status bar tooltip: "Stop dev server" 

The command palette command should also be "start/stop dev server" IMO. 

In either case, the terminology should be the same.

**Comment by RandomFractals** [comment]
Added `Dev` to `Start/Stop Server` command titles in #35.

I don't think capitalizing words in tooltips is good form, and tooltips should be more descriptive, although they might match commands sometimes.

Closing this as resolved.
