### ISSUE TITLE
Testing notes

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence-vscode#34]
Looking good. I like it a lot!

Some final QA from me.

## Port handling
EDIT: see #31 

~~If port 3000 is busy in another process, then vite uses 3001 (i was writing docs for evidence on another port).~~

~~However the VSCode extension always uses 3000.~~

~~Can we detect which port it opens and open the browser on that one?~~

![image](https://github.com/evidence-dev/evidence-vscode/assets/58074498/52c40c30-0f3a-4873-93b6-3be6bb4f3ff5)

## Commands

We have quite a lot of commands which can add a level of mental load to the user when choosing the right one. I think we might be able to reduce the number slightly

![image](https://github.com/evidence-dev/evidence-vscode/assets/58074498/3d76e6de-1f6f-4ef3-a278-61977aca57cc)

There are a couple of commands that feel a bit duplicative to me, so we might want to consider dropping them:

### Settings 
- View settings vs Open settings file
   - I understand these are different, but do we need VSCode shortcuts from them both?
   - I would probably remove the view settings one as there is a big button in the UI, though I am happy to hear the case if others disagree

### Dev server
- Preview vs Start Server
   - As an end user I don't really understand the difference here. They both boot the server up
   - Consider removing preview
     - (side note) In my mind, preview is what you do post build, if you want to drive around the built artifacts

**Comment by RandomFractals** [comment]
Commands clarifications for the above:

- `View Settings` displays your `Settings` page in Evidence app, and starts your dev server if it is not running. See #14 for more info. This is not available when the server is not running otherwise.
- `Open Settings` opens your actual `.evidence/template/evidence.settings.json` for manual editing and config in VS Code JSON editor. See #5 for implementation details. This is not available in your app at all.

**Comment by RandomFractals** [comment]
> Preview vs Start Server
> * As an end user I don't really understand the difference here. They both boot the server up
> * Consider removing preview
>   
>   * (side note) In my mind, preview is what you do post build, if you want to drive around the built artifacts

Resolved in #36.

**Comment by RandomFractals** [comment]
> ### Settings
> * View settings vs Open settings file
>   
>   * I understand these are different, but do we need VSCode shortcuts from them both?
>   * I would probably remove the view settings one as there is a big button in the UI, though I am happy to hear the case if others disagree

Resolved in #37
