### ISSUE TITLE
Hide display of Preview command in Command Palette...

### ISSUE THREAD

**Issue by RandomFractals** [evidence-dev/evidence-vscode#36]
to resolve general confusion about App `Preview` and `Start Server` commands, encountered during initial internal testing of v1.0.0. See initial review and test results feedback in #24 and #34 for more info.

- [x] Add `menus/commandPalette` contribution point to `package.json` and set `evidence.preview` command to `never` show there
- [ ] Update Commands pic in docs/images before releasing this feature in v1.1.0

**Comment by RandomFractals** [comment]
Trimmed down `Evidence:` commands list in vscode `Command Palette...` we can release in `v1.1.0`:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/956ad040-ed79-4716-ab48-744829936c90)

**Comment by archiewood** [comment]
Good solution thanks - and you can still get preview with shortcut or preview button.

**Comment by RandomFractals** [comment]
This is done. Commands image in docs will be updated when v1.1.0 is ready to be released.
