### ISSUE TITLE
Add `.evidence/template/evidence/settings.json` config to new projects created from Evidence template

### ISSUE THREAD

**Issue by RandomFractals** [evidence-dev/evidence-vscode#39]
- To initialize Evidence [`template`](https://github.com/evidence-dev/template) project after it is cloned in #2 
- To resolve current template app `needful_things.duckdb` data source config issues
- And to start a new project created from a template project without any errors or additional manual configuration/settings required

Related ticket with more info on that configuration: https://github.com/evidence-dev/evidence/issues/885#issuecomment-1567077927

We'll resolve this on our end by:

- [x] Adding the required `templateProjectSettings` json config to `commands/template.ts` implementation
- [x] Creating `.evidence/template/evidence.settings.json` file after a project is scaffolded from the github `template` project repo
- [x] And adding the required demo DuckdDB config to that file for the new project created from a template to start and run without any missing data or query errors

`.evidence/template/evidence.settings.json:`

```
{
  "database": "duckdb",
  "credentials": {
    "filename": "needful_things.duckdb",
    "gitignoreDuckdb": null
  }
}
```

- [x] We'll also refine all the `Create Project from Template` info messages, prompts and progress display UI parts for a better project starter navigation/creation UX flow

**Comment by archiewood** [comment]
This is the issue where we are tracking fixing this in the main evidence project:
https://github.com/evidence-dev/evidence/issues/804

**Comment by RandomFractals** [comment]
Reworked, patched up, and update Create Project from Template UX:

![evidence-create-project-from-template-4](https://github.com/evidence-dev/evidence-vscode/assets/656833/0e7d04cb-fa23-4ca5-a804-b9e9eced2fc3)

**Comment by RandomFractals** [comment]
New Create Project from Template prompt when a user tries to run it in existing project:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/1d43a1fe-8e38-4bc0-b9ca-bbd8d8d37082)
