### ISSUE TITLE
Allow creation of New Evidence project from anywhere

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence-vscode#47]
Not urgent

Extend https://github.com/evidence-dev/evidence-vscode/issues/2 to allow a user to create an evidence project without creating a new folder and opening it in vscode.

## Flow I can imagine:
1. Open command Palette
2. Select "Create evidence project from template"
3. prompt boots up asking where you want to create the new project (with sensible default location?)
4. Then prompt continues to ask about what you are cloning (default is template)
5. New (or current) VSCode window boots into new project directory
6. Clone and install happens

**Comment by RandomFractals** [comment]
We can't do it from anywhere. However, we can do it from VSCode File Explorer. That's how most extensions handle folder related actions.

Please see the feature ticket I created from our initial project scope and other notes, and use #48 for any comments and questions you might have about the planned feature implementation and navigation flow.
