### ISSUE TITLE
Add `Evidence: New Project` command and folder context menu options

### ISSUE THREAD

**Issue by RandomFractals** [evidence-dev/evidence-vscode#48]
Per our discussions and scope set for the phase 1 of interactive Evidence extension features, we'll add `Evidence: New Project` functionality.

## UX and Flow Details

- [x] Add new `evidence.newProject` command config to `package.json`
- [x] Add `New Evidence Project` context menu to folders in the File Explorer by adding `evidence.newProject` command to `menus: explorer:context []` commands and contribution point in extension `package.json` config
- [x] Add `NewEvidence` enum value to `Commands` to register enum in `commands.ts`
- [x] Create new `src/commands/project.ts` for the project command(s) implementation with `Select Folder` dialog when no new project folder Uri is provided
- [x] Display Open Dialog for the folder selection when this command is called from the `Command Palette...`
- [x] Display an Info message if the selected folder contains files, and prompt to create and use new empty workspace folder for the new Evidence project
- [x] Extend current project from template functionality from #2 to create New Evidence Project inside the **selected folder** in VS Code File Explorer
- [x] Clone Evidence `template` project to the selected empty workspace folder
- [x] Open new Evidence project folder in a new VS Code window.

**Comment by RandomFractals** [comment]
New Evidence Project command display in the Command Palette...

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/3eb0898d-5db0-444b-baa4-e4ad209e1b28)

**Comment by RandomFractals** [comment]
New Evidence Project command displayed for the selected folder in the built-in vscode File explorer context menu:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/753571e7-cb56-4b09-9dcb-2d301afae5b8)

**Comment by RandomFractals** [comment]
Select new project folder dialog display listing all the folders in an open workspace:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/54c20c5e-2ce3-486c-9744-43d7d6b4c5a2)

**Comment by RandomFractals** [comment]
Evidence extension Output view with the start of Create new project logging to trace this process:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/3236ce89-ea25-4991-9fad-92b0549aad06)

**Comment by RandomFractals** [comment]
Empty folder check, info message, and project folder dialog selection re-redisplay when the previously selected folder has files, or subfolders with files:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/82ace883-f135-4854-9368-6ebf6143e2d2)

**Comment by RandomFractals** [comment]
Create New Project in selected Folder with the default Evidence template project cloning below. I don't think this can be any simpler. We'll see if we should embed template project instead of cloning it from github in a separate ticket.

![evidence-new-project-2](https://github.com/evidence-dev/evidence-vscode/assets/656833/db442b62-a033-4c1a-a520-2fe9c228ac65)

**Comment by RandomFractals** [comment]
Some final notes on this New Project feature implementation for testing:

- We don't prompt for the template project github url to clone it for a new Evidence project
- Users can use the initial `Create Project from Template` feature to create new projects from their own Evidence app templates on github
- We don't prompt to install dependencies for the Evidence project created in an open Workspace with other files because we don't have support for the "nested" Evidence projects and files in an open workspace. See our new [Limitations](https://github.com/evidence-dev/evidence-vscode#limitations) section in docs for more info on this. We will update that section prior to `v1.1.0` final features release.

**Comment by RandomFractals** [comment]
The last part is now scripted too in #59, but users need to click ok to open newly ceated Evidence project in a new VS Code window:

![evidence-create-open-project-workflow-2](https://github.com/evidence-dev/evidence-vscode/assets/656833/9559509d-cf9a-4169-9287-326c6c769edd)

**Comment by RandomFractals** [comment]
Updated `New Project` Output view logging and display from #58:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/fb025e0f-1938-437f-8999-d09cd5e987f4)

**Comment by RandomFractals** [comment]
Changed Project is not empty notification to an error message in #61:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/c36ab0cd-103f-4ffb-b706-604a2829c37e)

**Comment by RandomFractals** [comment]
Creating New Project in an empty VS Code workspace from start to finish:

![evidence-new-project-empty-workspace-2](https://github.com/evidence-dev/evidence-vscode/assets/656833/b9c8bb26-c485-4795-9eb2-a8090a8a77d7)

**Comment by archiewood** [comment]
Issue with credentials

## Repro

1. Open a new workspace
2. add a folder that will contain evidence eg `reports`
3. right click `reports`-> Create new Evidence project

## Expected behaviour
No credentials are added in root folder

## Actual
Credentials are added at the root folder (not inside `reports` folder). 
These probably aren't harmful, but are confusing

![CleanShot 2023-06-05 at 14 35 18](https://github.com/evidence-dev/evidence-vscode/assets/58074498/c4f6438e-9274-4d96-b6cb-bb29e59615ca)

**Comment by RandomFractals** [comment]
@archiewood what do you mean by credentials? we don't modify any file or folder credentials anywhere in this vscode extension.

Are you referring to the `./evidence` folder created it at the top level of the open workspace folder?

**Comment by archiewood** [comment]
> Are you referring to the ./evidence folder created at the top level of the open workspace folder?
Yes

In this case it is not used, as it should be inside the child directory

**Comment by RandomFractals** [comment]
See most recent changes in #60 to address that. I will remove my settings.json copy from clone repo code.

**Comment by RandomFractals** [comment]
Tagging #65 to track it for v1.1.0 release

**Comment by RandomFractals** [comment]
@archiewood resolved your issue in the commit above. Also, please try creating new project from the built-in template. It's instant:

![evidence-project-from-template-3](https://github.com/evidence-dev/evidence-vscode/assets/656833/2a863c85-076a-40bf-9cdf-5d392557ead2)

**Comment by archiewood** [comment]
Yep works instantly for me as well. 🔥

Any reason we do not use this for the core "Create Evidence Project from template" command?

**Comment by RandomFractals** [comment]
Did not get to it 🙂  See #63 

Plus I was not sure how well it would work on the Mac and needed you to test it.

We can wrap it up in #63 today.
