### ISSUE TITLE
Remap `Evidence: View Settings` command we disabled to display extension settings in the built-in VS Code Settings editor

### ISSUE THREAD

**Issue by RandomFractals** [evidence-dev/evidence-vscode#55]
- [x] Enable `evidence.viewSettings` command we added in #14 and hid in #37 to show up in the `Command Palette...` VS Code menu
- [x] Change it to open built-in VS Code Settings editor and show `Evidence` Settings we added in #52, #53 and #54
- [x] Keep the old `ViewAppSettings` command in commands enum and change it to `evidence.viewAppSettings` for now
- [x] Add new `Commands.ViewExtensionSettings` enum value, and `viewExtensionSettings()` command implementation to `src/commands/settings.ts`
- [x] Update `Evidence: View Settings` command description in the `Commands` section in docs

**Comment by RandomFractals** [comment]
Update `Evidence: View Settings` command and display: 

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/24491862-0163-4964-9b05-1267ecb7aba6)

**Comment by RandomFractals** [comment]
Display remapped `Evidence: View Settings` command at all times, even when there is not Evidence project detected or created yet:

![image](https://github.com/evidence-dev/evidence-vscode/assets/656833/d1b8dd46-ba31-4837-9d6f-cdd7d0869308)

**Comment by archiewood** [comment]
✅
