### ISSUE TITLE
Start Server and Create project from template progress notification messages and display

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence-vscode#57]
Wasn't sure there was a good issue that covered both of these
These are pretty minor

## Start Server

- hangs around after the process finishes

![CleanShot 2023-06-02 at 15 19 35](https://github.com/evidence-dev/evidence-vscode/assets/58074498/097119c5-00de-4cc0-ae19-c44af4aa2193)

## Create project

- All on one line so you can't read all the text
- hangs around after the process finishes

<img width="542" alt="image" src="https://github.com/evidence-dev/evidence-vscode/assets/58074498/88c14ccc-c94d-483d-a336-1398276ba373">

**Comment by RandomFractals** [comment]
I'll resolve them by our release time next week.

Those are standard Information and Progress Notification messages. I know web apps use toasts lingo.

Just for future reference, VS Code docs have good page describing the different notification message types accessible to extension developers via their public api with some UX guidelines: 

https://code.visualstudio.com/api/ux-guidelines/notifications

**Comment by RandomFractals** [comment]
> ## Create project
> * All on one line so you can't read all the text
> * hangs around after the process finishes

Refined in #58. To resolve it completely we'll have to switch to embedding template project files in extension package or use different github cloning library that gives us better progress reporting. You an expand the Finished message step to see full message.

**Comment by RandomFractals** [comment]
> ## Start Server
> * hangs around after the process finishes

This is not reproducible in the latest version of this extension in this branch.

That install dependencies and start server two step process has been split earlier this week. I suspect you captured that with older rev. of this ext. prior to that install/start flow split.

Please more detailed list of steps in text along with screen captures next time, as it is not always clear of how you got it, and provide recordings in 2 or 3x speed. Sometimes it's hard to tell what is working or not when those gifs are reduced.

Here is what you should be seeing: 

![evidence-install-dependencies-start-flow](https://github.com/evidence-dev/evidence-vscode/assets/656833/b73f44b8-0cfe-4df7-b77f-f8355c10d313)

**Comment by RandomFractals** [comment]
Closing this as resolved. See #58 for the other issue you mentioned.
