### ISSUE TITLE
Modify Evidence Preview to render only markdown documents in `/pages/` folder

### ISSUE THREAD

**Issue by RandomFractals** [evidence-dev/evidence-vscode#67]
and use the built-in `markdown.showPreview` command from #29 to show preview of all other `.md` files that are not inside Evidence app `/pages/` folder.

- [x] Check `evidence.hasProject` context value to determine if the open workspace contains an Evidence project folder
- [x] Also, check if the requested preview page Uri contains `/page/` in its path. Assume those markdown documents are Evidence markdown documents
- [x] Render Evidence markdown documents by starting Evidence dev server and opening the requested page preview in the built-in simple browser webview
- [x] Render all other `.md` markdown documents using the built-in vscode markdown language features and `markdown.ShowPreview` command restored in #29
- [x] This should be resolved before we ship `v1.1.0` (#65) for proper default markdown documents preview handling

**Comment by RandomFractals** [comment]
The resulting Evidence and regular markdown documents Preview handling:

![evidence-markdown-documents-preview](https://github.com/evidence-dev/evidence-vscode/assets/656833/ddb842af-391f-4286-a0bd-35447b3c6427)

**Comment by archiewood** [comment]
On review, I think this is the issue I've noticed in #70

**Comment by RandomFractals** [comment]
That is correct. I will resolve it in #70 as it has more details capturing server start with `/` app path scenario.
