### ISSUE TITLE
Create new `/data` folder for the Evidence VS Code extension to store demo data, duckdb, parquet files, etc.

### ISSUE THREAD

**Issue by RandomFractals** [evidence-dev/evidence-vscode#69]
We'll use this new `/data` folder to store raw data files and demo DuckDB file versions for the new `/template` Evidence project we'll use to ship with this extenion.

- [x] Add raw `.parquet` data files
- [x] Create demo DuckDB file
- [x] Add/Include JS/Py `/scripts` or `/notebooks` folders depending on how DuckDB file creation is scripted.

We'll use the final parquet data files or duckdb file for the data part in #60

**Comment by archiewood** [comment]
I have added two slightly smaller data files to start
- orders.parquet - 6Mb
- needful_things.duckdb - 12.5MB

These are smaller just by nature of having one table vs all 5

If needed I can generate datasets with fewer rows which is the only way to reduce their size further

**Comment by archiewood** [comment]
I have a script which makes these files from CSVs - I can add this too

**Comment by RandomFractals** [comment]
@archiewood ideally, for the simple template project to copy, 1-2MB `.parquet` and/or `.duckdb` file would be much faster for us to clone from this repo when we scaffold new project.

Is there a way to cut them down to that size without breaking the samples pages and chart you have in that template project now?

**Comment by archiewood** [comment]
Done

**Comment by RandomFractals** [comment]
Looking good. Thank you!

Commit with smaller data files: https://github.com/evidence-dev/evidence-vscode/commit/65565aec2b14f260f175b39febc554a37975bb58
