### ISSUE TITLE
Add new Issue Templates to this Evidence VS Code extension repository

### ISSUE THREAD

**Issue by RandomFractals** [evidence-dev/evidence-vscode#74]
to gather feedback from the Evidence dev VS Code extension users about our new Interactive Evidence [MVP](https://github.com/evidence-dev/evidence-vscode/releases/tag/v1.0.0), and the upcoming `v1.1.0` release (#65)

- [ ] @archiewood, you can copy the [issue templates](https://github.com/evidence-dev/evidence/issues/new/choose) you have in your main app repo now

We would like to hear more from the Evidence dev users using VS Code IDE about their initial experience with our  `v1.0.0`, [published last week](https://marketplace.visualstudio.com/items?itemName=Evidence.evidence-vscode), and the next weekly enhancements and [onboarding](https://github.com/evidence-dev/evidence-vscode/issues?q=label%3Aonboarding) UX update in `v1.1.0` we'll be releasing today.

**Comment by archiewood** [comment]
I started with the feature request and bug templates to keep things simple

**Comment by RandomFractals** [comment]
ok. thanks! linking to them for now: https://github.com/evidence-dev/evidence-vscode/issues/new/choose

**Comment by RandomFractals** [comment]
Actually, can you please rename `Bug report` to `Issue report`?

Note every issue is a bug per our [review](https://github.com/evidence-dev/evidence-vscode/issues?q=label%3Areview+) tickets, etc.

**Comment by RandomFractals** [comment]
Not really, I think we'd like our users to report the issues they run into, we review and sort them out.
