### ISSUE TITLE
New project command deletes any existing contents

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence-vscode#75]
## Steps To Reproduce
- Use the Evidence: New Evidence Project command
- Select a folder that has existing contents

### Environment

- VSCode Extension version (Check in VSCode Marketplace): 1.1.0
- Node version (`node -v`): v18.12.1
- npm version (`npm -v`): 9.6.4
- OS: MacOS Ventura

## Expected Behavior

It fails and warns you that the file is not empty

## Actual Behaviour

It deletes all the files in the directory

```
Evidence dev server and extension logging output:

Creating new project ...
- New Project Folder: /Users/archie/Projects
- Template Project Folder: /Users/archie/.vscode/extensions/evidence.evidence-vscode-1.1.0/template

Creating project from template ...
- Template Project: /Users/archie/.vscode/extensions/evidence.evidence-vscode-1.1.0/template

✔ New project created successfully.
```

**Comment by archiewood** [comment]
Something is going wrong here https://github.com/evidence-dev/evidence-vscode/blob/0c46be615bc91167cc633cbb43d64f214beb8ce7/src/commands/project.ts#L70

**Comment by hughess** [comment]
Was able to reproduce. The console message I got references that the directory is not empty, but it uses `options.force` to override it:

<img width="1026" alt="CleanShot 2023-06-07 at 10 14 56@2x" src="https://github.com/evidence-dev/evidence-vscode/assets/12602440/5e2ef36f-f7a6-41c8-aa05-bebbac4e8049">

**Comment by hughess** [comment]
After a bit of debugging, I think what's happening is the check of `if(projectFiles.length > 0)` is not passing because the results of `await workspace.findFiles()` haven't been received yet

**Comment by RandomFractals** [comment]
@hughess both guesses are incorrect. 

The scenario @archiewood described requires a check when the default built-in `/template` added in #62 is used in an open workspace from the `Command Palette...` and extension creating new project at the root of that open workspace.

See #72 for more info and just add a check if the root open workspace folder has any files using the code snippets you have above before we copy all the files and subfolders from the built-in `/template` that ships with your extension to the 1st  workspace folder in the open workspace.

This was a last minute feature we flipped before releasing your `v1.1.0` Evidence dev [onboarding](https://github.com/evidence-dev/evidence-vscode/issues?q=is%3Aissue+label%3Aonboarding+) extension features and enhancements 

You should be able to easily patch it and release `v1.1.1` patch after bumping your ext. v. in `package.json` and providing the missing open workspace folder condition for one or both of the described cases (#72 & #62 while using #48 with #2).

I hope the notes shared in this comment will help your resolve this quickly as we move on to our next. 🤗

**Comment by archiewood** [comment]
Gif showing test protocol

![CleanShot 2023-06-07 at 14 33 28](https://github.com/evidence-dev/evidence-vscode/assets/58074498/f5d2f923-baef-463e-b881-b8e515a0b205)

**Comment by hughess** [comment]
@RandomFractals closed this for now - the changes fix the specific situation archie and i were running into. It seems like there might be another situation we need to cover as you've described - will open another issue for it
