### ISSUE TITLE
Prompt text

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence-vscode#80]
Would you like to install Evidence dev server dependencies?

-> 

Install required Evidence dependencies?

**Comment by hughess** [comment]
Are there situations where someone wouldn't want to install the dependencies?

Wondering if we should remove this prompt entirely and bundle the install deps action into the server starting command

**Comment by archiewood** [comment]
If you want to start the server, you will always want to install deps

I guess you might not bother and want to try to build immediately, so maybe we should bundle this here too

**Comment by hughess** [comment]
In #95 I've updated the `build` step so it automatically installs deps if they're not found, and then it continues the build. Previously, it was installing then stopping, so you'd need to run `build` again

**Comment by hughess** [comment]
Closed by #95
