### ISSUE TITLE
Throw more informative error if node is not installed

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence-vscode#81]
![CleanShot 2023-06-12 at 17 34 29](https://github.com/evidence-dev/evidence-vscode/assets/58074498/2d8cbf1d-3868-4d69-8e33-c7801ca5515c)

Suggest:

> Evidence requires Node.js. Install it [here](https://nodejs.org/en/download)

**Comment by archiewood** [comment]
Also you need to fully restart VSCode post installing Node.js for it to be accessible by VSCode (even if you can access it from a new terminal window)

**Comment by hughess** [comment]
Ah, having to restart VS Code will be annoying.

2 ways we could handle situations where node isn't installed:
1. In the walkthrough (#10), have the first step be a node version check, with a link to download node if we can't detect it
2. Include a node check at the beginning of the "Start Dev Server" command, which produces a pop-up with a download link when node isn't detected

**Comment by hughess** [comment]
When you do the same as you did in the gif, does anything under the "output" tab?

**Comment by hughess** [comment]
This might actually be fixed in `main` already
