### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence-vscode#89]
Keyboard shortcuts for common actions in Evidence (VS Code commands). E.g., start/stop dev server, build, etc.

**Comment by archiewood** [comment]
Cmd+Enter to run queries?

**Comment by archiewood** [comment]
Some common options ( I think these were from my C++ days)
- Start server: F5
- Stop server: Shift + F5
- Build: F7

Need to check they don't conflict with other stuff people want to do

**Comment by hughess** [comment]
A shortcut to run/stop the preview would also be great. Maybe something like `Cmd + E`, and the same can be used to start or stop the server (toggles it on/off - same as the button)

**Comment by archiewood** [comment]
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf
> - Start server: F5
> - Stop server: Shift + F5

This would be mapping our concept of dev server to the VSCode concept of debuging, which feels reasonable
